- src/TypeScriptGenerator.ts
- test/__snapshots__/TypeScriptGenerator-test.ts.snap
In cases where we cannot import the correct ref type,
declare it as any.
Related: #15
> [TS generator] Make sure the ref names are declared

- package.json
- src/TypeScriptGenerator.ts
- src/formatGeneratedModule.ts
- test/__snapshots__/TypeScriptGenerator-test.ts.snap
- test/fixtures/generated-module/complete-example.ts
This
* Renames `ConcreteFragment` to `FragmentReference`
* Disables all code related to fragment references until we get to #7
I’m going to self-merge this and cut a 0.9.0 version of the package (we can save v1 for when we have fragment references) so that I can start using that in our app properly.
> Bring artifacts up to date with DT part 2

- example/ts/__relay_artifacts__/AddTodoMutation.graphql.ts
- example/ts/__relay_artifacts__/ChangeTodoStatusMutation.graphql.ts
- example/ts/__relay_artifacts__/MarkAllTodosMutation.graphql.ts
- example/ts/__relay_artifacts__/RemoveCompletedTodosMutation.graphql.ts
- example/ts/__relay_artifacts__/RemoveTodoMutation.graphql.ts
- example/ts/__relay_artifacts__/RenameTodoMutation.graphql.ts
- src/TypeScriptTypeTransformers.ts
- test/__snapshots__/TypeScriptGenerator-test.ts.snap
Within an input object, if the type of a field is nullable, it should
then be optional within typescript as well as allowing `null` as an
explicit value. Conversely, if the type of a field is non-nullable, it
should be both required as a property and not allowed to be `null`.
> Fix property optionalism within Input Objects

- .travis.yml
@alloy has already enabled Travis for this repo, so this PR only needs to specify the configuration to run tests against. Based on [the Travis Node docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/), we should be okay to use the default `yarn` and `yarn test` installation/test steps, respectively. 
~This PR is a work-in-progress because I'm not sure if the initial tests will pass. We'll see!~
Fixes #23.
> Adds continuous integration tests.

- README.md
- package.json
- src/TypeScriptGenerator.ts
At Artsy we can’t migrate to latest Relay that easily, as I need to bring other PRs up to date as well, so going to make it backwards compatible for now.
> [plugin] Make plugin work with Relay < 1.6

- src/FindGraphQLTags.ts
- test/FindGraphQLTags-test.ts
tl;dr there is an off by one error in the parser. the test that existed didn't factor in that the first blank line of a tagged template literal counts as line 1.
Reproduction:
1. write a tag in the first line of a file *and start the tagged template literal with a tick on line 1*
2. run relay-compiler using the typescript parser
3. get the following error:
```
Parse error: Error: line in locationOffset is 1-indexed and must be positive in ...
```
PS may be worth publishing this one as a hotfix since it breaks builds
> fix oboe for source location line

- package.json
- src/FindGraphQLTags.ts
- src/TypeScriptGenerator.ts
- src/TypeScriptTypeTransformers.ts
- src/index.ts
- tslint.json
- yarn.lock
This PR adds TSLint, and also adds [lint-staged](https://github.com/okonet/lint-staged) precommit hooks for running TSLint and Prettier when committing files. I based the `tslint.json` config off of [Artsy's Reaction repo](https://github.com/artsy/reaction/blob/master/tslint.json) (minus JSX-specific rules), since @alloy would be familiar with its settings. I also added the following rules, which would've required non-trivial code changes.
- `forin`, which has a violation [here](https://github.com/relay-tools/relay-compiler-language-typescript/blob/cf9bcafdac0fedbdc8617ee1ff698c54a9ac637e/src/TypeScriptGenerator.ts#L139-L146).
- `no-shadowed-variable`, which has a violation [here](https://github.com/relay-tools/relay-compiler-language-typescript/blob/cf9bcafdac0fedbdc8617ee1ff698c54a9ac637 …
> Sets up TSLint, precommit hooks

- src/TypeScriptGenerator.ts
- test/TypeScriptGenerator-test.ts
- types/relay-compiler/language/RelayLanguagePluginInterface.d.ts
Implementation `noFutureProofEnums` as issue #80, #81.
Code ported from upstream as resolved in https://github.com/facebook/relay/issues/2351
This change allows to pass in CLI `--noFutureProofEnums` to avoid inclusion in enums of `"%future added value"`.
A test was added for this case, plus a small refactoring of test to keep it DRY and similar to upstream implementation.
@alloy @sibelius @steida
> Add support for noFutureProofEnums

- .gitignore
There's an issue w/ the deployment process caused by the .npmrc being added by ci but not being ignored by git. This should resolve that issue.
> Ignore npmrc

- .travis.yml
I had a bit of a hard time understanding where exactly [this error](https://travis-ci.org/relay-tools/relay-compiler-language-typescript/builds/498859485#L466) was coming from:
```
error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
```
…but I suppose it was due to us _always_ trying to configure NPM with an authentication token and it doesn't like it when it’s blank (eg when building from a fork)? 🤷‍♂️ 
Anyways, I think we only need this for deploying, so changing to `before_deploy` should probably be correct?
> [travis] Only configure NPM_TOKEN when deploying.

- .travis.yml
Fixes an issue where travis was removing `node_modules` before deployment. Specifying `skip_cleanup` will ensure dependencies are still around for auto to do its thing. 
Thanks @alloy for the extra eyeballs!
> Ensure dependencies are present so the release can succeed

- .travis.yml
@alloy this probably isn't ideal, but there have been some git failures when trying to deploy with auto about it begin detached from HEAD. I think it's because Travis checks out a hash and auto is trying to commit changelog entries and stuff. 
Hopefully this fixes it.
> Manually checkout master to fix git deploy fail

- .gitignore
- package.json
- test/__snapshots__/TypeScriptGenerator-test.ts.snap
- yarn.lock
With this PR I aim to start addressing outdated dependencies, this does not upgrade a few packages that cause breaking changes, and will upgrade those in a subsequent PR, so we can iterate. 
```
@types/jest
jest
jest-cli
ts-jest
relay-compiler
relay-runtime
relay-test-utils
```
> Have upgraded ^
For a future:
- Jest TypeScript probably require a new test-only tsconfig, so we can declare global the custo matcher. 
I also ran `npx sort-package-json`, to keep things nice and tidy. 🕺
> chore: Upgraded packages

- src/TypeScriptGenerator.ts
- src/TypeScriptTypeTransformers.ts
- test/TypeScriptGenerator-test.ts
- test/__snapshots__/TypeScriptGenerator-test.ts.snap
- types/relay-compiler/core/GraphQLIR.d.ts
- types/relay-compiler/language/RelayLanguagePluginInterface.d.ts
See the changes in the tests. This should allow much easier work with
types that can take many different shapes.
I assume this will fix #120.
> Re-port `selectionsToBabel` -> `selectionsToAST` to fixup union type decls

- scripts/deploy.sh
This adds the ability to configure the package publishing step via environment variables in travis. 
I've added `--dry-run` and `--verbose` flags via Travis' interface to temporarily disable the publishing step until we can dig into what's going wrong for auto
> Add the ability to configure auto deploys

- .travis.yml
- scripts/deploy.sh
The last thing remaining to fix the auto deploys is getting git pushes to work. 
I've added some extra configuration to the deploy script to ensure we can push to GitHub properly. The biggest thing now is ensuring that the token still has write access...
@alloy I'm not sure which is which in the tokens, but could you perhaps regenerate the GitHub token? Just to be on the safe side.
> Ensure CI can push to GitHub

- .travis.yml
- scripts/deploy.sh
It's me again. 
So there was another deployment fail because I was trying to set an upstream without fetching first.... 
Okay. Third time is the charm?
> Fix deployment issue by pulling before setting upstream

- .travis.yml
According to [this comment](https://github.com/intuit/auto/issues/624#issuecomment-544676295) our [previous failure](https://travis-ci.org/relay-tools/relay-compiler-language-typescript/builds/600835375?utm_source=github_status&utm_medium=notification) might be fixed by fetching the tags first. 
I won't force a release for this one, but once it goes through it'll be good to see if the release finishes without errors. It _should_ theoretically.
> Ensure tags are fetched for release

- src/formatGeneratedModule.ts
- test/fixtures/generated-module/complete-example.ts
- test/formatGeneratedModule-test.ts
The Flow language plugin emits a special [@relayHash pragma comment](https://github.com/relayjs/relay-examples/blob/205dfb195c770e7cd3977116654bd69c91d03b90/todo/__generated__/relay/AddTodoMutation.graphql.js#L3) that is [generated](https://github.com/facebook/relay/blob/597d2a17aa29d401830407b6814a5f8d148f632d/packages/relay-compiler/codegen/writeRelayGeneratedFile.js#L180) by the Relay compiler and is [utilized](https://github.com/facebook/relay/blob/597d2a17aa29d401830407b6814a5f8d148f632d/packages/relay-compiler/codegen/writeRelayGeneratedFile.js#L214) when running the compiler with the `--validate` flag.
This change adds the same code comment to the emitted TypeScript artifacts. 
Fixes #98.
> Support relay-compiler --validate

- src/formatGeneratedModule.ts
- test/fixtures/generated-module/complete-example-no-cast.ts
- test/fixtures/generated-module/complete-example.ts
tsling is slowly going to start deprecating itself in favour of integrating with eslint. So I dare say our consumers are slowly going to start adopting this. I know I have already moved there.
https://medium.com/palantir/tslint-in-2019-1a144c2317a9
> feat: Disable eslint for generated modules

- src/TypeScriptTypeTransformers.ts
- test/__snapshots__/TypeScriptGenerator-test.ts.snap
following on from https://github.com/relay-tools/relay-compiler-language-typescript/pull/140, this makes mutation inputs writable as well
> feat: make mutation inputs mutable

- scripts/deploy.sh
Fixes #167. 
There was a breaking change deployed in [auto](https://github.com/intuit/auto) and  the deploy script was automatically upgrading to the latest version. 
I'll be updating the config next week so I'll update the version then. I've set `$AUTO_VERSION` in circle to be `v7.6.0` which is what Artsy is running at the moment.
> Specify the version of auto or default to v7

- README.md
Should be https://github.com/relay-tools instead of https://github.com/kastermester
> Update example url in README

- example/README.md
There was no where in the readme that stated you needed to `yalc add relay-compiler-language-typescript` which if you've never used yalc is was confusing.
> Correct example installing steps

- src/TypeScriptGenerator.ts
- test/__snapshots__/TypeScriptGenerator-test.ts.snap
Closes: #182 
There are no circular dependency issues in the TS generator because it does not actually import the fragment, instead it references it using the `FragmentRefs` generic. [In comparison to how the Flow generator works](https://github.com/facebook/relay/blob/3457604b90ac160a164b9945ca6c23f0ab313fc1/packages/relay-compiler/language/javascript/RelayFlowGenerator.js#L988-L1004).
This means that generating the fragment **in** the query of a `@refetchable` is unnecessary.
> fix(TypeScriptGenerator): omit FragmentReference from refetchable query

- src/formatGeneratedModule.ts
- test/fixtures/generated-module/complete-example-no-cast.ts
- test/fixtures/generated-module/complete-example.ts
This would disable ts checking on the whole file for all output files to enable usage of `"importsNotUsedAsValues": "error"`. If needed I could spend some more time to make the change only target the imports, but since both tslint and eslint are disabled for the whole file I figured this could be an acceptable solution.
Fixes #177
> Disable ts-checks on output files

- .github/workflows/ci.yml
- package.json
- src/TypeScriptGenerator.ts
- src/TypeScriptTypeTransformers.ts
- src/addAnyTypeCast.ts
- test/FindGraphQLTags-test.ts
- test/TypeScriptGenerator-test.ts
- test/__snapshots__/TypeScriptGenerator-test.ts.snap
- test/ambient.d.ts
- test/fixtures/type-generator/mutation-with-append-prepend-edge.graphql
- test/formatGeneratedModule-test.ts
- tsconfig.build.json
- tsconfig.json
- yarn.lock
a lot of dependency updates got merged despite the build failing.
I tried to hotfix most things with ts-ignores, as well as breaking changes connections String -> ID.
Things are still far away from being optimal, but at least the build should not fail anymore...
> fix: bring package in a state where build and test do not fail

- .github/workflows/ci.yml
- src/TypeScriptGenerator.ts
- src/TypeScriptTypeTransformers.ts
- src/addAnyTypeCast.ts
This reverts the breaking changes I did in https://github.com/relay-tools/relay-compiler-language-typescript/pull/267 which broke Typescript < 4 support in 13.0.3 in a patch release :( (https://github.com/relay-tools/relay-compiler-language-typescript/issues/272).
We wanna release this as 13.0.5 then do a major release (14.0.0), which drops typescript < 4 support.
@alloy It seems like Travis CI automatically creates a release on every push on `master`. Could you explain how I could achieve a major version release? Is it based on commit messages? Maybe we should add a small contribution guide that explains how the deployment/changelog/versioning is done?
**Edit:** I just figured out this repo is using `auto`. Can you confirm that assigning the labels will trigger the right version bump …
> fix: revert breaking changes

- package.json
- tsconfig.json
As I mentioned in #305 I was using this library as a foundation for another compiler specific to next.js - noticed the types were missing, figured it couldn't hurt to output them.
> feat: include .d.ts types in release

- .autorc
- package.json
- scripts/deploy.sh
- yarn.lock
This fixes the issues encountered in https://github.com/relay-tools/relay-compiler-language-typescript/pull/275 where the deploy failed to increment the correct version.
I've implemented both fixes I suggested in the above issue. We both remove our dependency from Artsy's auto config (which lead to this original breakage) and bump the version of auto. 
As a validation of this process, I've added the Trivial label which means this build should generate no release.
> Remove artsy auto-config dep, update auto pinned version

- package.json
- yarn.lock
- build: upgrade relay-compiler
- build: upgrade relay-runtime
- build: upgrade relay-test-utils-internal
- build: upgrade @types/relay-compiler
- build: upgrade @types/relay-runtime
- build: upgrade babel-plugin-relay
- build: updgrade @types/react-relay peer-dep
> build: upgrade to relay v12

- src/loadCompilerOptions.ts
This PR resolves the relative `basePath` parameter passed to `ts.parseJsonConfigFileContent()`.
Despite setting the correct `target` and `module` versions in `tsconfig.json`, the `replaceRequire` option was never being set.
As it turned out, `loadCompilerOptions` was failing to parse our `tsconfig.json` correctly - the following error was causing it to return an empty object (despite the parsed config having a valid `options` property):
```
{
file: undefined,
start: undefined,
length: undefined,
messageText: `No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["dist"]'.`,
category: 1,
code: 18003,
reportsUnnecessary: undefined,
reportsDeprecated: undefined
}
```
We don't explicitly specify the `files` or `include` keys …
> Resolve `basePath` parameter to prevent errors when loading compiler options

- README.md
- package.json
- src/TypeScriptGenerator.ts
- yarn.lock
This is a breaking change as it wont work with older TypeScript versions!
closes #513
> Fixing TypeScript 4.5 type generation

- README.md
Add note to `README.md` that this repository is obsolete.
After merging the following steps are required:
#581
> [Chore] add note that this repository is obsolete
