relay-tools/relay-compiler-language-typescript

.gitignore, README.md, example/.gitignore, example/ts/__generated__/appQuery.graphql.ts, example/ts/components/__generated__/TodoApp_viewer.graphql.ts, example/ts/components/__generated__/TodoListFooter_viewer.graphql.ts, example/ts/components/__generated__/TodoList_viewer.graphql.ts, example/ts/components/__generated__/Todo_todo.graphql.ts, example/ts/components/__generated__/Todo_viewer.graphql.ts, example/ts/mutations/__generated__/AddTodoMutation.graphql.ts, example/ts/mutations/__generated__/ChangeTodoStatusMutation.graphql.ts, example/ts/mutations/__generated__/MarkAllTodosMutation.graphql.ts, example/ts/mutations/__generated__/RemoveCompletedTodosMutation.graphql.ts, example/ts/mutations/__generated__/RemoveTodoMutation.graphql.ts, example/ts/mutations/__generated__/RenameTodoMutation.graphql.ts
=> [example] Import generated artifacts.

test/ambient.d.ts
Will make `TypeScriptGenerator-tests.ts`  compile with `tsc`
=> Adds an ambient declaration for the expect extension

src/TypeScriptGenerator.ts, src/TypeScriptTypeTransformers.ts, test/__snapshots__/TypeScriptGenerator-test.ts.snap, yarn.lock
https://github.com/facebook/relay/commit/6d49a52050069dd45f422fdb054092b1bbdda9b8#diff-183e387ea6bf165c686b6fa30dc40812
Fixes #44.
Supercedes #45.
=> [plugin] Port stack overflow fix.

example/package.json, example/ts/__relay_artifacts__/AddTodoMutation.graphql.ts, example/ts/__relay_artifacts__/ChangeTodoStatusMutation.graphql.ts, example/ts/__relay_artifacts__/MarkAllTodosMutation.graphql.ts, example/ts/__relay_artifacts__/RemoveCompletedTodosMutation.graphql.ts, example/ts/__relay_artifacts__/RemoveTodoMutation.graphql.ts, example/ts/__relay_artifacts__/RenameTodoMutation.graphql.ts, example/ts/__relay_artifacts__/TodoApp_viewer.graphql.ts, example/ts/__relay_artifacts__/TodoListFooter_viewer.graphql.ts, example/ts/__relay_artifacts__/TodoList_viewer.graphql.ts, example/ts/__relay_artifacts__/Todo_todo.graphql.ts, example/ts/__relay_artifacts__/Todo_viewer.graphql.ts, example/ts/__relay_artifacts__/appQuery.graphql.ts, example/yarn.lock, package.json, src/TypeScriptGenerator.ts, src/TypeScriptTypeTransformers.ts, test/__snapshots__/TypeScriptGenerator-test.ts.snap, yarn.lock
Depends on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27867.
=> Adds type-checking support for fragment references.

README.md
=> [CI] Adds badge to readme.

example/package.json, example/ts/__relay_artifacts__/AddTodoMutation.graphql.ts, example/ts/__relay_artifacts__/ChangeTodoStatusMutation.graphql.ts, example/ts/__relay_artifacts__/MarkAllTodosMutation.graphql.ts, example/ts/__relay_artifacts__/RemoveCompletedTodosMutation.graphql.ts, example/ts/__relay_artifacts__/RemoveTodoMutation.graphql.ts, example/ts/__relay_artifacts__/RenameTodoMutation.graphql.ts, example/ts/__relay_artifacts__/appQuery.graphql.ts, example/ts/app.tsx, example/ts/mutations/AddTodoMutation.ts, example/ts/mutations/ChangeTodoStatusMutation.ts, example/ts/mutations/MarkAllTodosMutation.ts, example/ts/mutations/RemoveCompletedTodosMutation.ts, example/ts/mutations/RemoveTodoMutation.ts, example/ts/mutations/RenameTodoMutation.ts, example/yarn.lock, package.json, src/TypeScriptGenerator.ts, test/__snapshots__/TypeScriptGenerator-test.ts.snap
Makes it easy to use the new typings of QueryRenderer and commitMutation https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28379
=> Emit combined operation typings that can be used with generics

src/TypeScriptGenerator.ts, test/TypeScriptGenerator-test.ts, test/__snapshots__/TypeScriptGenerator-test.ts.snap
=> [plugin] Type fragment refs as any when not using a single artifact dir.

README.md
I'm not a best english writer so maybe that can be a starting point for you at least :)
=> Add README section about react-hot-loader problem

.travis.yml, package.json
Updates the deploy command to use bash directly
=> Update deploy command

.travis.yml, src/TypeScriptGenerator.ts, test/__snapshots__/TypeScriptGenerator-test.ts.snap, test/fixtures/type-generator/fragment-spread.graphql
=> Typing common fields on interfaces

src/TypeScriptGenerator.ts, test/__snapshots__/TypeScriptGenerator-test.ts.snap
Fixes #113
https://github.com/facebook/relay/blob/eb221c4a7e01e05a4e144eb8729db0f533995a2e/packages/relay-compiler/language/javascript/RelayFlowGenerator.js#L417
=> [generator] Add support for `@match` directive.

.gitignore, package.json, src/TypeScriptTypeTransformers.ts, test/__snapshots__/TypeScriptGenerator-test.ts.snap, test/fixtures/type-generator/unknown-scalar.graphql, yarn.lock
With unknown scalars, instead of marking them as `any`, we should be marking them as ts unknown. 
This branch is a branch from PR #123, and should be merged before this one.
=> feat: Annotated unknown fields as ts unknown

src/TypeScriptGenerator.ts
=> chore: Rectify spelling mistakes

scripts/deploy.sh
Whack-a-mole...
Okay, let's make sure we set the upstream. 🙄
=> Fix failing deployments by adding the proper  git upstream

.travis.yml
Still having issues with the upstream branch...
In this update I've ensured that master is checked out _and_ that the local master branch is explicitly stated when set upstream is called.
=> Ensure on master, and that upstream is pointed at master

src/TypeScriptGenerator.ts, test/__snapshots__/TypeScriptGenerator-test.ts.snap
This PR solves #158 partially, changing the order of enum definitions.
=> Fix enum import order

package.json, src/TypeScriptGenerator.ts, test/__snapshots__/TypeScriptGenerator-test.ts.snap, yarn.lock
=> Fix duplicate imports

.github/workflows/ci.yml, README.md, package.json, src/TypeScriptGenerator.ts, src/TypeScriptTypeTransformers.ts, src/addAnyTypeCast.ts, test/fixtures/generated-module/complete-example-no-cast.ts, test/fixtures/generated-module/complete-example.ts, test/formatGeneratedModule-test.ts, yarn.lock
This reverts commit 4b88ffa0b34a52341a66e7f09562fbecda0a0b53.
Thanks to auto we again published patch changes as a major release.
=> Revert "feat: drop typescript 3 and Node.js 10 support (#275)"

package.json, tsconfig.json, yarn.lock
It looks like immutable package is not used in this project.
=> Drop immutable

.github/workflows/release.yml
This is a follow up to #407 and should fix #405.
=> Add missing github token

.github/workflows/ci.yml, package.json
- ci: use node v16
- ci: use actions/cache@v2
- run prettier check
=> ci: use node 16 for tests and run prettier check

example-hooks/yarn.lock, example/yarn.lock, yarn.lock
Upgraded all sub dependencies via `yarn upgrade --deep`
=> Upgrade sub dependencies

README.md, src/formatGeneratedModule.ts
Feature request, I'm not wed to this particular implementation but figured it was the easiest way to ask. ^_^
=> feat: adding the ability to include a custom header on generated files
